// ReSharper disable All
using System;
using System.Diagnostics.CodeAnalysis;
using RE_Editor.Models.Enums;

namespace RE_Editor.Constants;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "IdentifierTypo")]
public static class ItemConstants {
    public const uint ACID_ROUNDS = 38;
    public const uint ASSAULT_COIN = 302;
    public const uint ASSAULT_RIFLE_AMMO = 33;
    public const uint AUDIOCASSETTE_TAPE = 131;
    public const uint AUDIOCASSETTE_TAPE_2 = 213;
    public const uint BATTERY = 161;
    public const uint BATTERY_PACK = 186;
    public const uint BLUE_JEWEL = 188;
    public const uint BOLT_CUTTERS = 152;
    public const uint CASE = 185;
    public const uint CRAFTING_COMPANION = 304;
    public const uint CULTURE_SAMPLE = 234;
    public const uint DETONATOR = 166;
    public const uint DETONATOR_2 = 217;
    public const uint DOT_SIGHT_HANDGUN = 77;
    public const uint DUAL_MAGAZINE_ASSAULT_RIFLE = 97;
    public const uint ELECTRONIC_GADGET = 165;
    public const uint EXPLOSIVE_A = 63;
    public const uint EXPLOSIVE_B = 64;
    public const uint EXPLOSIVE_ROUNDS = 37;
    public const uint EXTENDED_BARREL_MAG = 101;
    public const uint EXTENDED_MAGAZINE_HANDGUN = 78;
    public const uint FANCY_BOX = 192;
    public const uint FANCY_BOX_2 = 193;
    public const uint FANCY_BOX_3 = 194;
    public const uint FIRE_HOSE = 181;
    public const uint FIRE_HOSE_2 = 264;
    public const uint FIRST_AID_SPRAY = 1;
    public const uint FLAME_ROUNDS = 39;
    public const uint FLASH_DRIVE = 232;
    public const uint FUSE = 222;
    public const uint FUSE_2 = 223;
    public const uint FUSE_3 = 224;
    public const uint GREEN_HERB = 2;
    public const uint GREEN_HERB_2 = 22;
    public const uint GREEN_JEWEL = 187;
    public const uint GUNPOWDER = 61;
    public const uint HANDGUN_AMMO = 31;
    public const uint HIGH_GRADE_GUNPOWDER = 62;
    public const uint HIP_POUCH = 261;
    public const uint HOSPITAL_ID_CARD = 211;
    public const uint HOSPITAL_MAP = 250;
    public const uint ID_CARD = 164;
    public const uint IRON_DEFENSE_COIN = 301;
    public const uint KENDOS_GATE_KEY = 182;
    public const uint KEY = 162;
    public const uint KEY_2 = 218;
    public const uint LIQUID_FILLED_TEST_TUBE = 235;
    public const uint LOCK_PICK = 151;
    public const uint MAG_AMMO = 34;
    public const uint MAP_OF_DOWNTOWN_RC = 247;
    public const uint MINE_ROUNDS = 36;
    public const uint MIXED_HERB_G_PLUSG = 5;
    public const uint MIXED_HERB_G_PLUSG_PLUSG = 9;
    public const uint MIXED_HERB_G_PLUSR = 6;
    public const uint MODERATOR_HANDGUN = 76;
    public const uint NEST_2_MAP = 253;
    public const uint POLICE_DEPARTMENT_MAP = 246;
    public const uint RECOVERY_COIN = 303;
    public const uint RED_HERB = 3;
    public const uint RED_HERB_2 = 23;
    public const uint RED_JEWEL = 189;
    public const uint STARS_FIELD_COMBAT_MANUAL = 305;
    public const uint SCOPE_ASSAULT_RIFLE = 96;
    public const uint SEMI_AUTO_BARREL_SHOTGUN = 91;
    public const uint SEWERS_MAP = 249;
    public const uint SHELL_HOLDER_SHOTGUN = 93;
    public const uint SHOTGUN_SHELLS = 32;
    public const uint SUBSTATION_MAP = 248;
    public const uint SUPPLY_CASE = 311;
    public const uint SUPPLY_CASE_2 = 312;
    public const uint SUPPLY_CASE_3 = 313;
    public const uint SUPPLY_CASE_4 = 314;
    public const uint SUPPLY_CASE_5 = 315;
    public const uint SUPPLY_CASE_6 = 316;
    public const uint TACTICAL_GRIP_ASSAULT_RIFLE = 98;
    public const uint TACTICAL_STOCK_SHOTGUN = 92;
    public const uint TAPE_PLAYER = 214;
    public const uint TAPE_PLAYER_TAPE_INSERTED = 212;
    public const uint UNDERGROUND_STORAGE_MAP = 252;
    public const uint VACCINE = 233;
    public const uint VACCINE_BASE = 236;
    public const uint VACCINE_SAMPLE = 215;
    public const uint WRISTBAND = 231;
}
