//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHR_Editor.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Assets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Assets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MHR_Editor.Data.Assets", typeof(Assets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ARMOR_DESC_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("ARMOR_DESC_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ARMOR_NAME_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("ARMOR_NAME_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ARMOR_SERIES_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("ARMOR_SERIES_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CAT_DOG_ARMOR_DESC_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("CAT_DOG_ARMOR_DESC_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CAT_DOG_ARMOR_NAME_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("CAT_DOG_ARMOR_NAME_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CAT_DOG_WEAPON_DESC_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("CAT_DOG_WEAPON_DESC_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CAT_DOG_WEAPON_NAME_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("CAT_DOG_WEAPON_NAME_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DANGO_DESC_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("DANGO_DESC_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DANGO_NAME_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("DANGO_NAME_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DANGO_SKILL_NAME_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("DANGO_SKILL_NAME_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DECORATION_DESC_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("DECORATION_DESC_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DECORATION_NAME_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("DECORATION_NAME_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GC_TITLE_DESC_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("GC_TITLE_DESC_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GC_TITLE_NAME_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("GC_TITLE_NAME_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ITEM_DESC_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("ITEM_DESC_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ITEM_NAME_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("ITEM_NAME_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PETALACE_DESC_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("PETALACE_DESC_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PETALACE_NAME_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("PETALACE_NAME_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RAMPAGE_DECORATION_DESC_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("RAMPAGE_DECORATION_DESC_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RAMPAGE_DECORATION_NAME_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("RAMPAGE_DECORATION_NAME_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RAMPAGE_SKILL_NAME_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("RAMPAGE_SKILL_NAME_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SKILL_ENUM_NAME_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("SKILL_ENUM_NAME_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SKILL_NAME_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("SKILL_NAME_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] STRUCT_INFO {
            get {
                object obj = ResourceManager.GetObject("STRUCT_INFO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SWITCH_SKILL_DESC_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("SWITCH_SKILL_DESC_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SWITCH_SKILL_NAME_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("SWITCH_SKILL_NAME_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WEAPON_DESC_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("WEAPON_DESC_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WEAPON_NAME_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("WEAPON_NAME_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
